'use strict';
const $=s=>document.querySelector(s), esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let entries=[],sources=[],category='',seniorOnly=false;
const normalize=s=>s.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
function matches(e,q){const text=normalize([e.title,e.category,e.description,e.code,e.note,e.platform||'',...(e.signals||[]),...(e.steps||[]),e.success||'',...e.sources].join(' '));return q.split(/\s+/).every(x=>text.includes(x))}
function render(){const q=normalize($('#search').value.trim()), filtered=entries.filter(e=>(!category||category===e.category)&&(!seniorOnly||e.senior)&&matches(e,q));$('#result-title').textContent=category||(q?'Resultados da busca':'Todos os assuntos');$('#result-count').textContent=`${filtered.length} referências`;
$('#clear').hidden=!q&&!category&&!seniorOnly;$('#empty').hidden=filtered.length>0;const cats=[...new Set(filtered.map(e=>e.category))];$('#results').innerHTML=cats.map(cat=>`<div class="group"><div class="group-heading">${esc(cat)}</div>${filtered.filter(e=>e.category===cat).map(e=>`<details id="ref-${e.id}"><summary><div><div class="item-title">${esc(e.title)}${e.senior?'<span class="senior-tag">SRE sênior</span>':''}</div><div class="item-desc">${esc(e.description)}</div></div><span class="expand" aria-hidden="true">+</span></summary><div class="detail-body"><div class="code-head"><span>${cat==='Catálogo de comandos'?'COMANDOS E DESCRIÇÕES':e.senior?'EXEMPLO / ROTEIRO TÉCNICO':'REFERÊNCIA DE COMANDOS'}</span><button class="copy" data-copy="${e.id}">Copiar</button></div>${e.platform?`<p class="platform">${esc(e.platform)}</p>`:''}<pre><code>${esc(e.code)}</code></pre>${e.senior?`<div class="senior-content"><section><h3>Sinais e interpretação</h3><ul>${e.signals.map(t=>`<li>${esc(t)}</li>`).join('')}</ul></section><section><h3>Sequência de investigação</h3><ol>${e.steps.map(t=>`<li>${esc(t)}</li>`).join('')}</ol></section><section class="success"><h3>Critério de validação</h3><p>${esc(e.success)}</p></section></div>`:''}<p class="context">${esc(e.note)}</p><div class="sources">${e.senior?'REFERÊNCIAS OFICIAIS · SÍNTESE E EXEMPLOS DIDÁTICOS':'ORIGEM DA CONSOLIDAÇÃO'}<br>${e.sources.map(s=>`<span class="source-pill">${esc(s)}</span>`).join('')}${(e.references||[]).map(r=>`<a class="reference-link" href="${esc(r.url)}" target="_blank" rel="noopener noreferrer">${esc(r.title)}</a>`).join('')}</div></div></details>`).join('')}</div>`).join('');document.querySelectorAll('nav button').forEach(b=>b.classList.toggle('active',b.dataset.category===category));}
function nav(){const cats=[...new Set(entries.map(e=>e.category))];$('#categories').innerHTML=[['', 'Todos os assuntos'],...cats.map(c=>[c,c])].map(([v,label])=>`<button data-category="${esc(v)}"><span style="color:inherit;font-size:14px">${esc(label)}</span><span>${v?entries.filter(e=>e.category===v).length:entries.length}</span></button>`).join('');$('#entry-count').textContent=entries.length;$('#category-count').textContent=cats.length;}
$('#senior-only').addEventListener('change',()=>{seniorOnly=$('#senior-only').checked;render()});$('#search').addEventListener('input',render);$('#categories').addEventListener('click',e=>{const b=e.target.closest('button');if(b){category=b.dataset.category;render()}});$('.quick').addEventListener('click',e=>{if(e.target.dataset.query){$('#search').value=e.target.dataset.query;category='';render()}});$('#clear').addEventListener('click',()=>{$('#search').value='';category='';seniorOnly=false;$('#senior-only').checked=false;render()});$('#source-toggle').addEventListener('click',()=>{$('#source-panel').hidden=!$('#source-panel').hidden;$('#source-toggle').setAttribute('aria-expanded',String(!$('#source-panel').hidden));if(!$('#source-panel').hidden)$('#source-panel').scrollIntoView({behavior:'smooth',block:'start'})});
$('#results').addEventListener('click',async e=>{const b=e.target.closest('[data-copy]');if(!b)return;try{await navigator.clipboard.writeText(entries.find(x=>x.id===b.dataset.copy).code);b.textContent='Copiado';setTimeout(()=>b.textContent='Copiar',1800)}catch{b.textContent='Selecione o texto';}});document.addEventListener('keydown',e=>{if(e.key==='/'&&!['INPUT','TEXTAREA'].includes(document.activeElement.tagName)){e.preventDefault();$('#search').focus()}});
Promise.all([fetch('data.json').then(r=>{if(!r.ok)throw Error();return r.json()}),fetch('sources.json').then(r=>{if(!r.ok)throw Error();return r.json()})]).then(([a,b])=>{entries=[...a.filter(e=>e.senior),...a.filter(e=>!e.senior)];sources=b;nav();$('#source-list').innerHTML=sources.map(s=>`<div class="source-row"><span>${esc(s.file)}<small>${esc(s.status)}</small></span><span>${s.entries} referências</span></div>`).join('');render()}).catch(()=>{$('#result-count').textContent='Não foi possível carregar o acervo. Recarregue a página.'});
